<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Payments\Remove\" />
    <Folder Include="Features\Properties\DeleteMedia\" />
    <Folder Include="Features\Properties\Queries\GetPropertyDetails\" />
    <Folder Include="Features\Properties\Save\" />
    <Folder Include="Features\Properties\UploadMedia\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abwaab.Domain\Abwaab.Domain.csproj" />
  </ItemGroup>

</Project>
