<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Properties\DeleteMedia\**" />
    <Compile Remove="Features\Properties\UploadMedia\**" />
    <EmbeddedResource Remove="Features\Properties\DeleteMedia\**" />
    <EmbeddedResource Remove="Features\Properties\UploadMedia\**" />
    <None Remove="Features\Properties\DeleteMedia\**" />
    <None Remove="Features\Properties\UploadMedia\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Appointments\Cancel\" />
    <Folder Include="Features\Appointments\Complete\" />
    <Folder Include="Features\Appointments\Report\" />
    <Folder Include="Features\Appointments\Refuse\" />
    <Folder Include="Features\Payments\Remove\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abwaab.Domain\Abwaab.Domain.csproj" />
  </ItemGroup>

</Project>
