<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Mappings\" />
    <Folder Include="DTOs\Profile\UserNotificationWays\" />
    <Folder Include="DTOs\Profile\UpgradPlan\" />
    <Folder Include="DTOs\Profile\UpdateInfo\" />
    <Folder Include="Features\Properties\" />
    <Folder Include="Features\Users\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abwaab.Domain\Abwaab.Domain.csproj" />
  </ItemGroup>

</Project>
