namespace Abwaab.Application.Common.Constants;

public static class ErrorTitle
{
    public const string LoggingUser = "تسجيل الدخول";
    public const string InitiateEmailChange = "تغيير البريد الاكتروني";
    public const string InitiatePhoneChange = "تغيير رقم الهاتف";
    public const string RegisterUser = "إنشاء حساب";
    public const string ChangePassword = "تغيير كلمة المرور";
    public const string VerificationCode = "تأكيد رمز التحقق";
    public const string ConfirmPayment = "تأكيد عملية الدفع";
    public const string AddingProperty = "إضافة عقار";
    public const string CancelUserPlan = "إلغاء الاشتراك بخطة";
    public const string UpgradeUserPlan = "ترقية الاشتراك";
    public const string ConfirmEmailChange = "تأكيد عملية تغيير البريد الالكتروني";
    public const string CancelEmailChange = "إلغاء تغيير البريد الالكتروني";
    public const string NotificationWaySubscription = "الاشتراك بطريقة إشعارات";
    public const string NotificationWayUnsubscription = "إلغاء الاشتراك بطريقة إشعارات";
    public const string ConfirmPhoneNoChange = "تأكيد عملية تغيير رقم الهاتف";
    public const string CancelPhoneNoChange = "إلغاء تغيير رقم الهاتف";
    public const string RefreshToken = "رمز التحديث";
    public const string AssignRoleToUser = "إسناد دور إلى مستخدم";
    public const string RemoveUserFromRole = "سحب دور من مستخدم";
    public const string SendCode = "إرسال رمز تحقق";
    public const string GetUserRoles = "استعلام عن أدوار المستخدم";
    public const string LogoutUser = "تسجيل خروج المستخدم";
    public const string ProfileData = "معلومات المستخدم";
    public const string UpdateUser = "تعديل بيانات المستخدم";
    public const string UpdateProperty = "تعديل بيانات العقار";
    public const string PropertyQuery = "استعلام عن عقار";
    public const string UploadMedia = "تحميل ملف وسائط";
    public const string DeleteMedia = "حذف ملف وسائط";
    public const string StarProperty = "تمييز عقار";
    public const string UnstarProperty = "إلغاء تمييز عقار";
    public const string SaveProperty = "حفظ العقار للنشر";
    public const string PropertiesQuery = "الاستعلام عن العقارات";
    public const string RejectProperty = "رفض عقار";
    public const string AcceptProperty = "الموافقة على عقار";
    public const string DisableProperty = "إلغاء تفعيل عرض عقار";
    public const string EnableProperty = "إعادة تفعيل عرض عقار";
    public const string PropertyDetails = "تفاصيل العقار";
    public const string TimeSlotsQuery = "الاستعلام عن الأوقات المتاحة للزيارة";
    public const string BookAppointment = "حجز موعد زيارة عقار";
    public const string ConfirmAppointment = "تأكيد موعد زيارة عقار";
    public const string UserAppointments = "الاستعلام عن المواعيد";
    public const string SellProperty = "تأكيد بيع العقار";
    public const string DeleteProperty = "حذف العقار";
    public const string GetUserNotifications = "الاستعلام عن إشعارات المستخدم";
    public const string MainPage = "الصفحة الرئيسية";
    public const string PendingProperties = "العقارات المعلقة";
}
